FORMAT: 1A
HOST: https://example.aibnb.com/

# Aibnb

All backend related rest API sits here.

## Search By Country [/search?country={?country}&latitude={?latitude}&longitude={?longitude}&zipcode={?zipcode}&page={page}&page_count={page_count}]
+ Parameters
    + country (string) - Search parameter for the country
    + latitude (number) - Latitude of a place
    + longitude (number) - Longitude of a place
    + zipcode (number) - Zipcode of a place
    + page (number, required) - Send a page number to view the data
    + page_count (number) - Get data from a page. Default is 30.

### Get data from each country [GET]


### Assumptions: 
1. Assume that price is always dollars
2. The endpoint should accept any of country,latitude,longitude or zipcode parameters

+ Response 200 (application/json)

        {
            "data": [
                {
                    "listing_id": "2818",
                    "name": "Quiet Garden View Room & Super Fast WiFi",
                    "summary": "Quiet Garden View Room & Super Fast WiFi",
                    "price": "69.00", 
                    "reviews_per_month": 2.1,
                    "has_availability": "true",
                    "availability_30": 17,
                    "availability_60": 43,
                    "availability_90": 57,
                    "availability_365": 90
                    "number_of_reviews": 243,
                    
                },
                {
                    "listing_id": "2830",
                    "name": "Quiet Garden View Room & Super Fast WiFi",
                    "summary": "Quiet Garden View Room & Super Fast WiFi",
                    "price": "69.00", 
                    "reviews_per_month": 2.1,
                    "has_availability": "true",
                    "availability_30": 17,
                    "availability_60": 43,
                    "availability_90": 57,
                    "availability_365": 90
                    "number_of_reviews": 243,
                    
                }
            ],
            "page_count": 30,
            "total_count": 1000,
            "page": 1
        }
        
## Search By Listing Id [/search/listingId={listingId}]

### Get data from each listing id [GET]

### Assumptions: 
1. Assume that price is always dollars

+ Response 200 (application/json)

                {
                    "listing_id": "2818",
                    "name": "Quiet Garden View Room & Super Fast WiFi",
                    "summary": "Quiet Garden View Room & Super Fast WiFi",
                    "picture_url": "https://a0.muscache.com/im/pictures/10272854/8dcca016_original.jpg?aki_policy=large",
                    "street": "Amsterdam, North Holland, Netherlands",
                    "neighbourhood": "Indische Buurt",
                    "city": "Amsterdam",
                    "state":"North Holland",
                    "zipcode": "1059",
                    "country_code": "NL",
                    "country": "Netherlands",
                    "latitude": 52.39022505,
                    "longitude": 4.941419235,
                    "property_type": "Apartment",
                    "room_type": "Private room",
                    "accommodates": 2,
                    "bathrooms": 1.5,
                    "bedrooms": 1,
                    "beds": 2,
                    "amenities": [
                        "Internet,Wifi",
                        "Paid parking off premises",
                        "Buzzer/wireless intercom",
                        "Heating,Washer",
                        "Smoke detector",
                        "Carbon monoxide detector",
                        "First aid kit",
                        "Safety card",
                        "Fire extinguisher",
                        "Essentials,Shampoo",
                        "Lock on bedroom door",
                        "24-hour check-in",
                        "Hangers",
                        "Hair dryer",
                        "Iron",
                        "Laptop friendly workspace",
                        "translation missing: en.hosting_amenity_49",
                        "translation missing: en.hosting_amenity_50",
                        "Private entrance",
                        "Hot water",
                        "Bed linens",
                        "Extra pillows and blankets",
                        "Single level home",
                        "Garden or backyard",
                        "Step-free access",
                        "Flat path to front door",
                        "Well-lit path to entrance",
                        "Step-free access",
                        "Accessible-height bed",
                        "Step-free access",
                        "Host greets you",
                        "Handheld shower head"
                        ],
                    "price": "69.00", 
                    "reviews_per_month": 2.1,
                    "has_availability": "true",
                    "availability_30": 17,
                    "availability_60": 43,
                    "availability_90": 57,
                    "availability_365": 90
                    "number_of_reviews": 243,
                    
                }